train: ./datasets/train/images  # train images
val: ./datasets/valid/images  # val images
test:  # test images (optional)

# Classes
nc: 3  # number of classes
names: ['with_mask', 'without_mask', 'mask_weared_incorrect']  # class names
